SETLOCAL
@ECHO OFF

SET COMPONENT_NAME=SIDTLB
SET COMPONENT_TYPE=LIBRARY

SET THIS=%~dp0
SET COMPONENT_DESCRIPTION=%COMPONENT_NAME%@%COMPONENT_TYPE%

ECHO. >> %INSTALL_LOGFILE%
ECHO  ^>^>^> %COMPONENT_DESCRIPTION% ^>^>^> >> %INSTALL_LOGFILE%
ECHO  ^>^>^> %COMPONENT_DESCRIPTION% ^>^>^>
ECHO. >> %INSTALL_LOGFILE%

COPY "%THIS%\sidtlb.dll" "%INSTALL_BIN_SXS%" 1>> %INSTALL_LOGFILE% 2>>&1
COPY "%THIS%\Tenaris.SxS.SIDTLB.manifest" "%INSTALL_BIN_SXS%" 1>> %INSTALL_LOGFILE% 2>>&1
COPY "%THIS%\Tenaris.Library.SIDLib.Interop.dll" "%INSTALL_BIN%" 1>> %INSTALL_LOGFILE% 2>>&1

if exist "%ProgramFiles(x86)%" ( 
	REGEDIT /S "%THIS%\..\..\config\HKLM-SOFTWARE-x64-SIDERCA-SIL.reg"
) else ( 
	REGEDIT /S "%THIS%\..\..\config\HKLM-SOFTWARE-SIDERCA-SIL.reg"
)

ECHO. >> %INSTALL_LOGFILE%
ECHO  ^>^>^> DONE ^>^>^> >> %INSTALL_LOGFILE%
ECHO  ^>^>^> DONE ^>^>^>
ECHO. >> %INSTALL_LOGFILE%

ENDLOCAL
